DROP TABLE PARTICIPANT;

CREATE TABLE PARTICIPANT (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(30) NOT NULL,
	ADRRESS VARCHAR(50),
	CITY VARCHAR(50),
	PHONE VARCHAR(20),
	VERSION INT,
	PRIMARY KEY (ID)
);

DROP TABLE APP_USER;

CREATE TABLE APP_USER (
	ID INT NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30) NOT NULL,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD_HASH VARCHAR(72) NOT NULL,
	USER_TYPE INT NOT NULL,
    STATUS INT,  
    PARTICIPANT_FK INT,
    CHANGED_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CHANGED_BY_APP_USER_FK INT,
	FORCE_PASS_CHANGE VARCHAR(1),
	INVALID_LOGIN_ATTEMPT INT,
	LAST_VALID_LOGIN TIMESTAMP,
	LAST_INVALID_LOGIN TIMESTAMP,
	LAST_PASS_CHANGED_DT TIMESTAMP,
	USER_EMAIL VARCHAR(100),
	PASS_POLICY_FK INT,
	VERSION INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (PARTICIPANT_FK) REFERENCES PARTICIPANT(ID) ON DELETE CASCADE
);

DROP TABLE APP_FUNCTION;

CREATE TABLE APP_FUNCTION (
	ID INT NOT NULL AUTO_INCREMENT,
	FUNCTION_NAME VARCHAR(50),
	URLS VARCHAR(1000),
	PRIMARY KEY (ID)
);

DROP TABLE APP_ROLE;

CREATE TABLE APP_ROLE (
	ID INT NOT NULL AUTO_INCREMENT,
	ROLE_NAME VARCHAR(50) NOT NULL,
	PARTICIPANT_FK INT NOT NULL,
	VERSION INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (PARTICIPANT_FK) REFERENCES PARTICIPANT(ID) ON DELETE CASCADE
);

DROP TABLE APP_ROLE_APP_FUNCTION;

CREATE TABLE APP_ROLE_APP_FUNCTION (
	ID INT NOT NULL AUTO_INCREMENT,
	APP_ROLE_FK INT,
	APP_FUNCTION_FK INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (APP_ROLE_FK) REFERENCES APP_ROLE(ID) ON DELETE CASCADE,
	FOREIGN KEY (APP_FUNCTION_FK) REFERENCES APP_FUNCTION(ID) ON DELETE CASCADE
);

DROP TABLE APP_USER_APP_ROLE;

CREATE TABLE APP_USER_APP_ROLE (
	ID INT NOT NULL AUTO_INCREMENT,
	APP_USER_FK INT,
	APP_ROLE_FK INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (APP_USER_FK) REFERENCES APP_USER(ID) ON DELETE CASCADE,
	FOREIGN KEY (APP_ROLE_FK) REFERENCES APP_ROLE(ID) ON DELETE CASCADE
);

DROP TABLE PASS_POLICY;

CREATE TABLE PASS_POLICY
(
   ID INT NOT NULL AUTO_INCREMENT,
   VERSION INT DEFAULT 0 NOT NULL,
   CHANGED_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   CHANGED_BY_APP_USER_FK INT,
   NAME VARCHAR(30) NOT NULL,
   PARTICIPANT_FK INT,
   PASS_MIN_PERIOD_IN_DAYS INT,
   PASS_MAX_PERIOD_IN_DAYS INT,
   PASS_MIN_LENGTH INT,
   PASS_MIN_HISTORY_REPEAT INT,
   PASS_LOGIN_ATTEMPT INT,
   PASS_BLOCK_WAIT_TIME INT,
   PASS_MUST_HAVE_LOWERCASE VARCHAR(1) DEFAULT 'N',
   PASS_MUST_HAVE_NUMBER VARCHAR(1) DEFAULT 'N',
   PASS_MUST_HAVE_UPPERCASE VARCHAR(1) DEFAULT 'N',
   PASS_MUST_HAVE_SPECIAL_CHARS VARCHAR(1) DEFAULT 'N',
   PASS_UNBLOCK_AUTOMATICALLY VARCHAR(1) DEFAULT 'N',
   PASS_SPECIAL_CHARS VARCHAR(20),
   PRIMARY KEY (ID),
   FOREIGN KEY (CHANGED_BY_APP_USER_FK) REFERENCES APP_USER(ID) ON DELETE CASCADE
);

DROP TABLE PASS_HISTORY;

CREATE TABLE PASS_HISTORY
(
   ID INT NOT NULL AUTO_INCREMENT,
   CHANGED_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   APP_USER_FK INT NOT NULL,
   PASSWORD_HASH VARCHAR(72) NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (APP_USER_FK) REFERENCES APP_USER(ID) ON DELETE CASCADE
);

DROP TABLE APP_CONFIG;

CREATE TABLE APP_CONFIG
(
   ID INT NOT NULL AUTO_INCREMENT,
   PARTICIPANT_FK INT,
   PARAM_NAME VARCHAR(30) NOT NULL,
   PARAM_VALUE VARCHAR(100) NOT NULL,
   PARAM_DESC VARCHAR(500),
   PRIMARY KEY (ID),
   FOREIGN KEY (PARTICIPANT_FK) REFERENCES PARTICIPANT(ID) ON DELETE CASCADE
);

DROP TABLE ACTIVITY_LOG;

CREATE TABLE ACTIVITY_LOG
(
   ID INT NOT NULL AUTO_INCREMENT,
   APP_USER_FK INT,
   DURATION INT,
   URL VARCHAR(200),
   DATETIME_START TIMESTAMP,
   ACTIVITY_DATA VARCHAR(3500),
   USER_IP VARCHAR(40),
   THREAD_NAME VARCHAR(30),
   PARTICIPANT_FK INT,
   ERROR_NO INT,
   PRIMARY KEY (ID),
   FOREIGN KEY (APP_USER_FK) REFERENCES APP_USER(ID) ON DELETE CASCADE,
   FOREIGN KEY (PARTICIPANT_FK) REFERENCES PARTICIPANT(ID) ON DELETE CASCADE
);

DROP TABLE AUDIT_LOG;

CREATE TABLE AUDIT_LOG
(
   ID INT NOT NULL AUTO_INCREMENT,
   AUDIT_TIMESTAMP TIMESTAMP,
   TABLE_NAME VARCHAR(50),
   UPDATE_STRING VARCHAR(3500),
   APP_USER_FK INT,
   AUDIT_TYPE VARCHAR(25),
   AUDIT_STATUS INT,
   PARTICIPANT_FK INT,
   PRIMARY KEY (ID),
   FOREIGN KEY (APP_USER_FK) REFERENCES APP_USER(ID) ON DELETE CASCADE,
   FOREIGN KEY (PARTICIPANT_FK) REFERENCES PARTICIPANT(ID) ON DELETE CASCADE
);

INSERT INTO APP_FUNCTION(ID, FUNCTION_NAME, URLS)  VALUES (1, 'USER_VIEW', '/app/appUser/view*|/app/appUser/list');
INSERT INTO APP_FUNCTION(ID, FUNCTION_NAME, URLS)  VALUES (2, 'USER_UPDATE', '/app/appUser/view*|/app/appUser/add*|/app/appUser/list|/app/appUser/save*|/app/appUser/delete*');

INSERT INTO APP_FUNCTION(ID, FUNCTION_NAME, URLS)  VALUES (3, 'ROLE_VIEW', '/app/appRole/view*|/app/appRole/list');
INSERT INTO APP_FUNCTION(ID, FUNCTION_NAME, URLS)  VALUES (4, 'ROLE_UPDATE', '/app/appRole/view*|/app/appRole/add*|/app/appRole/list|/app/appRole/save*|/app/appRole/delete*');

INSERT INTO APP_FUNCTION(ID, FUNCTION_NAME, URLS)  VALUES (5, 'PASS_POLICY_VIEW', '/app/passPolicy/view*|/app/passPolicy/list');
INSERT INTO APP_FUNCTION(ID, FUNCTION_NAME, URLS)  VALUES (6, 'PASS_POLICY_UPDATE', '/app/passPolicy/view*|/app/passPolicy/add*|/app/passPolicy/list|/app/passPolicy/save*|/app/passPolicy/delete*');

INSERT INTO app_user (ID,FIRST_NAME,LAST_NAME,USERNAME,PASSWORD_HASH,STATUS,PARTICIPANT_FK,VERSION,USER_TYPE,CHANGED_DT,CHANGED_BY_APP_USER_FK,FORCE_PASS_CHANGE,INVALID_LOGIN_ATTEMPT,last_valid_login,last_invalid_login,LAST_PASS_CHANGED_DT,USER_EMAIL,PASS_POLICY_FK) VALUES (1,'Milan','Mitic','milan','$2a$10$38soDYodVHr3hMqKLh1xdeJ8zGZ3OzDYk.TkSE5FRjL3Z9ReXD4vu',1,null,62,0,{ts '2017-06-19 00:11:27.'},1,null,0,{ts '2017-06-19 00:11:27.'},{ts '2017-06-19 00:11:27.'},{ts '2017-06-18 20:39:14.'},null,1);
